# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator('^1[3-9]\\d{9}$', '手机号码格式错误')]),
        ),
    ]
