# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190120_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.ImageField(default='default/qqlogin.png', upload_to='shop/%Y%m/%d'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, '昵称至少两位')]),
        ),
    ]
