# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号必须为11位')])),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8, '密码最小长度为8位')])),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, '用户名至少两位')])),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('Hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
