# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='首页活动名称')),
                ('picture_address', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='图片地址')),
                ('url_site', models.URLField(verbose_name='活动的url地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='活动专区名称')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动专区的简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=0, verbose_name='上否上线')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_address', models.ImageField(upload_to='goods_pictures/%Y%m/%d', verbose_name='商品图片地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品相册管理',
                'verbose_name_plural': '商品相册管理',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品分类管理',
                'verbose_name_plural': '商品分类管理',
            },
        ),
        migrations.CreateModel(
            name='Goods_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100, verbose_name='商品sku名')),
                ('breif', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('logo', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='封面图片')),
                ('is_shelf', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=False, verbose_name='是否上架')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Activity', verbose_name='活动分类')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Commodity', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品sku管理',
                'verbose_name_plural': '商品sku管理',
            },
        ),
        migrations.CreateModel(
            name='Goods_spu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_name', models.CharField(max_length=50, verbose_name='商品spu名')),
                ('content', models.TextField(verbose_name='商品详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品spu名',
                'verbose_name_plural': '商品spu名',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20, verbose_name='商品单位')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品单位',
                'verbose_name_plural': '商品单位',
            },
        ),
        migrations.CreateModel(
            name='Wheel_planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='轮播活动名称')),
                ('picture_address', models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播图片管理',
                'verbose_name_plural': '轮播图片管理',
            },
        ),
        migrations.AddField(
            model_name='goods_sku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_spu', verbose_name='商品spu'),
        ),
        migrations.AddField(
            model_name='goods_sku',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Unit', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='album',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_sku', verbose_name='商品sku'),
        ),
        migrations.AddField(
            model_name='activityzone',
            name='goods_sku',
            field=models.ManyToManyField(to='goods.Goods_sku', verbose_name='商品'),
        ),
    ]
