# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 21:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityzone',
            options={'verbose_name': '特色专区管理', 'verbose_name_plural': '特色专区管理'},
        ),
        migrations.AlterField(
            model_name='activityzone',
            name='is_on_sale',
            field=models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=0, verbose_name='是否上线'),
        ),
        migrations.AlterField(
            model_name='goods_spu',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情'),
        ),
    ]
